import Navbar from "./components/layouts/navbar/Navbar";
import "./globals.css";
import { Roboto } from 'next/font/google'

export const metadata = {
  title: "RW Piscinas de fibra",
  description: "Generated by mendezz",
};


const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
