import Navbar from "./components/layouts/navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "RW Piscinas de fibra",
  description: "Generated by mendezz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
