export const piscinas = [
    {
      id: 1,
      name: "Piscina Luxo",
      description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
      price: 15000,
      installmentPrice: 1300,
      dimensions: "8m x 4m",
      imageUrl: '/images/piscinas/Violeta 2x2.png',
      benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
      cardPriceStyle: { color: "red" },
      modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
    },
    {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "red", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },   
       {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
    // outros objetos de piscina...
  ];
  