export const piscinas = [
    {
      id: 1,
      name: "VIOLETA",
      description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
      price: 7500,
      installments: 12,
      installmentPrice: 752.56,
      dimensions: "2,00 x 2,00 x 0,70",
      imageUrl: '/images/piscinas/Violeta 2x2.png',
      benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
    },
    {
        id: 2,
        name: 'GÉRBERA',
        dimensions: '3.00 X 2.00 X 0.80',
        price: 7500,
        installments: 12,
        installmentPrice: 752.56,
        imageUrl: '/images/piscinas/Gerbera 3.00 x 2.00.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
      },
      {
        id: 3,
        name: 'CÁSPIA',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installments: 12,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },   
       {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installments: 12,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installments: 12,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
      {
        id: 2,
        name: 'Piscina Fada 7.50 x 5.00',
        dimensions: '11.00 X 5.50 X 2.20',
        price: 35000,
        installmentPrice: 2916.67,
        imageUrl: '/images/piscinas/Girassol 2.20 x 2.20.png',
        description: "Um design elegante com tecnologia de ponta. Ideal para quem busca conforto e sofisticação em sua casa.",
        benefits: ["Garantia de 10 anos", "Instalação premium", "Resistente a intempéries"],
        cardPriceStyle: { color: "#333", fontWeight: "normal" },
        modalPriceStyle: { color: "#d32f2f", fontWeight: "bold" },
      },
    // outros objetos de piscina...
  ];
  